{% set name = "python-ace" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ICAMS/{{ name }}/archive/d1c213a7d9c5b809a3ae83b2e5a916be26d921f0.tar.gz
  sha256: 8ff9471ff9c659b038a924ace5cc6b50db993885568043b0650c427c79543508
  patches:
    - pybind.patch
    - grace.patch
    - setup.patch
    - numpy.patch
    - pandas.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3
  skip: true  # [win or py>312]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - pybind11
  run:
    - python
    - ase
    - numpy <3
    - setuptools <81
    - pandas >=2,<4
    - psutil
    - ruamel.yaml
    - libcxx  # [osx]
    - scikit-learn
    - grace-tensorpotential

test:
  imports:
    - pyace
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ICAMS/python-ace/
  summary: 'pacemaker - a tool for fitting of interatomic potentials in a general nonlinear Atomic Cluster Expansion (ACE) form'
  description: |
    pacemaker - a tool for fitting of interatomic potentials in a general
    nonlinear Atomic Cluster Expansion (ACE) form.
  license: ASL
  license_family: OTHER
  license_file: LICENSE.md
  doc_url: https://pacemaker.readthedocs.io
  dev_url: https://github.com/ICAMS/python-ace/

extra:
  recipe-maintainers:
    - srmnitc
    - jan-janssen
